### ISSUE TITLE
Before you Get Started

### ISSUE THREAD

**Issue by marceloogeda** [avizmarlon/google-interview-university#1]
I'll work on this chunk.

**Comment by avizmarlon** [comment]
Sure, thanks. 

Make sure you read [this](https://github.com/jwasham/google-interview-university/issues/113). Its just some small guidelines to make sure we don't have merge conflicts and have a consistent translation.

I'm currently not working on any chunk (been pretty busy). I'll soon post the chunk I'll work on.

**Comment by marceloogeda** [comment]
Let me know if I need to do something else to close this issue.

**Comment by avizmarlon** [comment]
Nope, all good. I was just waiting for your input on the minor changes I made to your work to see if you accepted it. Closing issue. Ty!
