### ISSUE TITLE
Translation file updated according to changes in original file.

### ISSUE THREAD

**Issue by avizmarlon** [avizmarlon/google-interview-university#10]
Hey @marceloogeda, @garri-ribeiro, @laris151

Just letting you know I've updated the translation file ([readme-ptbr.md](https://github.com/avizmarlon/google-interview-university/blob/ptbr-translation/translations/README-ptbr.md)) according to the changes John Washan made to his original file (he mostly removed stuff related to Google). Don't forget to pull/merge before making new changes.

Check the changes below:
- https://github.com/avizmarlon/google-interview-university/commit/a616bbe65bc931482993a558441181e291fd93e5
- https://github.com/avizmarlon/google-interview-university/commit/09ad22ecddc5101994ae13f16adc72fe940d4ee3
- https://github.com/avizmarlon/google-interview-university/commit/6966a7208b8617ccc8d3eba5c05c6f35b8322be9

**Comment by marceloogeda** [comment]
Sure! Don't worry, I'm following the changes. Thank you ;)
